'use strict';

/**
 * minioClient.js
 *
 * Singleton MinIO client. Exports a pre-configured Minio.Client instance
 * and a helper `uploadDirectory()` function that recursively uploads an
 * entire local directory tree to a MinIO bucket under a given key prefix.
 *
 * All buckets default to PRIVATE (no public read policy). Access to objects
 * is controlled exclusively via signed/presigned URLs generated by the API
 * server (Phase 2).
 */

const Minio  = require('minio');
const fs     = require('fs');
const path   = require('path');
const logger = require('./logger');

// ─────────────────────────────────────────────────────────────────────────────
// Client Configuration
// All values are injected via environment variables — never hard-coded.
// ─────────────────────────────────────────────────────────────────────────────
const client = new Minio.Client({
  endPoint:        process.env.MINIO_ENDPOINT   ?? 'localhost',
  port:            parseInt(process.env.MINIO_PORT ?? '9000', 10),
  useSSL:          process.env.MINIO_USE_SSL    === 'true',
  accessKey:       process.env.MINIO_ACCESS_KEY,
  secretKey:       process.env.MINIO_SECRET_KEY,
});

const VIDEOS_BUCKET = process.env.MINIO_BUCKET ?? 'videos';
const KEYS_BUCKET   = process.env.MINIO_KEYS_BUCKET ?? 'encryption-keys';

/**
 * Ensures both required buckets exist. Called once at worker startup.
 * MinIO's `makeBucket` is idempotent — safe to call on every boot.
 */
async function ensureBucketsExist() {
  for (const bucket of [VIDEOS_BUCKET, KEYS_BUCKET]) {
    const exists = await client.bucketExists(bucket);
    if (!exists) {
      await client.makeBucket(bucket, process.env.MINIO_REGION ?? 'us-east-1');
      logger.info(`Created MinIO bucket: ${bucket}`);
    }
  }
}

/**
 * Uploads a single file to a MinIO bucket.
 *
 * @param {string} bucket     - Target bucket name
 * @param {string} objectName - The key/path inside the bucket
 * @param {string} filePath   - Absolute local path to the file
 * @param {object} [meta={}]  - Optional custom metadata (stored as S3 user metadata)
 */
async function uploadFile(bucket, objectName, filePath, meta = {}) {
  const stat = fs.statSync(filePath);
  const stream = fs.createReadStream(filePath);

  await client.putObject(bucket, objectName, stream, stat.size, {
    'Content-Type': inferContentType(filePath),
    ...meta,
  });

  logger.debug(`Uploaded ${filePath} → minio://${bucket}/${objectName}`);
}

/**
 * Recursively walks a local directory and uploads every file to MinIO,
 * preserving the directory structure under the given `prefix`.
 *
 * @param {string} localDir   - Absolute path to the local directory
 * @param {string} bucket     - Target MinIO bucket
 * @param {string} prefix     - Key prefix inside the bucket (e.g., "videos/abc123")
 * @returns {Promise<number>} - Total number of files uploaded
 */
async function uploadDirectory(localDir, bucket, prefix) {
  const entries = fs.readdirSync(localDir, { withFileTypes: true });
  let count = 0;

  for (const entry of entries) {
    const localPath  = path.join(localDir, entry.name);
    const objectName = `${prefix}/${entry.name}`;

    if (entry.isDirectory()) {
      count += await uploadDirectory(localPath, bucket, objectName);
    } else {
      await uploadFile(bucket, objectName, localPath);
      count++;
    }
  }

  return count;
}

/**
 * Uploads the AES-128 encryption key binary to the private keys bucket.
 * The key is stored separately from video segments so access can be
 * controlled independently (served only to authenticated users by the API).
 *
 * @param {string} videoId  - The unique video identifier
 * @param {Buffer} keyBuf   - The raw 16-byte AES key
 */
async function uploadEncryptionKey(videoId, keyBuf) {
  await client.putObject(
    KEYS_BUCKET,
    `${videoId}/enc.key`,
    keyBuf,
    keyBuf.length,
    { 'Content-Type': 'application/octet-stream' }
  );
  logger.info({ videoId }, 'Encryption key stored in MinIO (private bucket)');
}

/** Infer MIME type from file extension for proper Content-Type headers */
function inferContentType(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  const map = {
    '.m3u8': 'application/vnd.apple.mpegurl',
    '.ts':   'video/MP2T',
    '.key':  'application/octet-stream',
    '.mp4':  'video/mp4',
  };
  return map[ext] ?? 'application/octet-stream';
}

module.exports = {
  client,
  VIDEOS_BUCKET,
  KEYS_BUCKET,
  ensureBucketsExist,
  uploadFile,
  uploadDirectory,
  uploadEncryptionKey,
};
